### ISSUE TITLE
Run "run_cmd" after k3s service

### ISSUE THREAD

**Issue by ssro** [rancher/k3os#148]
Hi folks,

Is it possible that `run_cmd` be executed after k3s service initialization? Right now, if I would like to deploy from a yaml file, written to disk or from an URL, or run a kubectl command, it will fail, because `k3s.service` starts after the script has been executed. 
Workarounds for this would be ok too.

In case one wants to reproduce this, create a `config.yaml` file and create a script which will run a command (can be a deployment or any other kubectl command), for example:

```
write_files:
- encoding: ""
  content: |-
    #!/bin/bash
    kubectl get nodes
  owner: root
  path: /etc/kube.sh
  permissions: '0755'
hostname: k3os
run_cmd:
- "/etc/kube.sh"

k3os:
  data_sources:
  - aws
  - cdrom
  modules:
  - kvm
  - nvme
  password: rancher
  k3s_args:
  - server
  - "--no-deploy traefik"
  - "--no-deploy servicelb"
```

Setup k3os to use the file and boot it. Attached is a screenshot where one can see that the script fails to run (kubectl get nodes), then few lines down, k3s service is started.

![Screen Shot 2019-07-17 at 11 18 26 PM](https://user-images.githubusercontent.com/13402690/61392541-3fa2f000-a8e9-11e9-9db4-fd16675b59d4.png)

Thanks!
