### ISSUE TITLE
[Question] k3os.k3s_args are not used to ignite the cluster?

### ISSUE THREAD

**Issue by Moep90** [rancher/k3os#298]
After installing to disk, I hoped to have a k3s server up + running.
But k3s_args seam to have no effekt, right? Any advices?

I used the `v0.7.1`
I have to start the server manual by running the following after boot:
cli 
```bash
k3s server --flannel-backend ipsec --write-kubeconfig /var/lib/rancher/k3s/server/kubeconfig.json
```
Or via run_cmd:
```bash
run_cmd: |
  k3s server
  --flannel-backend ipsec
  --write-kubeconfig /var/lib/rancher/k3s/server/kubeconfig.json
```

k3s version:
```bash
$ k3s --version
k3s version v1.0.0 (18bd921c)
```
Kubectl
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

```
ssh_authorized_keys:
 [...]
write_files:
# - encoding: "UTF-8"
#   content: |-
#     #!/bin/bash
#     echo hi
#   owner: root
#   path: /etc/rc.local
#   permissions: '0755'
hostname: k3s-master
run_cmd: |
  "export MASTER_IP=$(ifconfig eth0 | grep "inet " | awk -F'[: ]+' '{ print $4 }')"
k3os:
  modules:
  - kvm
  - nvme
  sysctl:
    kernel.printk: 4 4 1 7
    kernel.kptr_restrict: 1
 [...]
  k3s_args:
    - server
    - "--flannel-backend ipsec"
    - "--write-kubeconfig /var/lib/rancher/k3s/server/kubeconfig.json"
  environment:
  taints:
    - key1=value1:NoSchedule
    - key1=value1:NoExecute

```
