### ISSUE TITLE
[CloudInit][HA-Setup] consider allowing external datastore to be specified with cloud-init

### ISSUE THREAD

**Issue by Moep90** [rancher/k3os#308]
**Is your feature request related to a problem? Please describe.**
When trying to setup K3OS as HA with three Master Nodes, the dqlite is still experimental.
So I would like to use an external datastore beeing implemented in cloud-init

**Describe the solution you'd like**
I would like to see those implemented into cloud-init:
```
K3S_DATASTORE_ENDPOINT
--datastore-endpoint
K3S_DATASTORE_CAFILE
--datastore-cafile
K3S_DATASTORE_CERTFILE
--datastore-certfile
K3S_DATASTORE_KEYFILE 
--datastore-keyfile
```
So that I can for example do the following:
```
[...]
k3os:
  datastore:
    cafile:
    cert:
    key:
[...]
```
[Parameters can be found here](https://rancher.com/docs/k3s/latest/en/installation/datastore/#external-datastore-configuration-parameters)

**Describe alternatives you've considered**
Using the CLI is still fine

**Additional context**
Since dqlite is experientel it would be nice to specify external datastore in the bootstrap process.

**Comment by dweomer** [comment]
@Moep90 what you’re looking for is https://github.com/rancher/k3os#k3osk3s_args

**Comment by Moep90** [comment]
> @Moep90 what you’re looking for is https://github.com/rancher/k3os#k3osk3s_args

I couldn't find "datastore" there. Is it possible to just add it like the following:
```
k3os:
  datastore:
    endpoint: mysql://username:password@tcp(hostname:3306)/database-name
    cafile: my.ca.file.cert
    certfile: my.cert.file.cert
    keyfile: my.key.file.cert
 data_sources:
  - aws
  - cdrom
  modules:
  - kvm
  - nvme
  sysctl:
    kernel.printk: 4 4 1 7
    kernel.kptr_restrict: 1
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  wifi:
  - name: home
    passphrase: mypassword
  - name: nothome
    passphrase: somethingelse
  password: rancher
```

**Comment by zimme** [comment]
```
k3os:
  k3s_args:
    - server
    - "--datastore-endpoint=<datastore-endpoint-url>"
    - "--datastore-cafile=<cafile>"
    - "<all the other datastore options>"
    - "..."
```
I'm pretty sure this is what @dweomer meant @Moep90.

**Comment by dweomer** [comment]
> ```
> k3os:
>   k3s_args:
>     - server
>     - "--datastore-endpoint=<datastore-endpoint-url>"
>     - "--datastore-cafile=<cafile>"
>     - "<all the other datastore options>"
>     - "..."
> ```
> 
> I'm pretty sure this is what @dweomer meant @Moep90.

Yes, exactly.

---
Also, please consider https://github.com/rancher/k3os#k3osenvironment for k3s arguments that can alternatively be passed as environment variables. So, instead of:
```
k3os:
  k3s_args:
    - server
    - "--datastore-endpoint=<endpoint-url>"
    - "--datastore-cafile=<cafile>"
    - "--datastore-certfile=<certfile>"
    - "--datastore-keyfile=<keyfile>"
    - "..."
```
you would have:
```
k3os
  environment:
    K3S_DATASTORE_ENDPOINT: "<endpoint-url>"
    K3S_DATASTORE_CAFILE: "<cafile>"
    K3S_DATASTORE_CERTFILE: "<certfile>"
    K3S_DATASTORE_KEYFILE: "<keyfile>"
```

I tend to favor envvars, when available, because they let me unclutter the service command-line.
