### ISSUE TITLE
More and better documentation needed for k3os.k3s_args

### ISSUE THREAD

**Issue by pagong** [rancher/k3os#315]
**Is your feature request related to a problem? Please describe.**
I've spent several days, trying to get `k3s` options, that had worked with `k3os <= v0.2.1`, working again with `k3os >= v0.3.0`. I was struggling with cluster-cidr and service-cidr options, that take an additional value as argument. But this relates to all `k3s` options that take additional values.

**Describe the solution you'd like**
The following `config.yaml` does no longer work:
```
hostname: rancher225
k3os:
   k3s_args:
  - server
  - "--cluster-cidr 10.107.0.0/23"
  - "--service-cidr 10.107.1.0/23"
```
`k3s` does not start up properly and logs strange error messages to `/var/log/k3s-service.log`.

**Describe alternatives you've considered**
The following `config.yaml` using '=' does work, and should be documented:
```
hostname: k3os060a
k3os:
  environment:
    http_proxy: http://192.168.107.9:8080
    https_proxy: http://192.168.107.9:8080
    no_proxy: localhost,127.0.0.1,192.168.107.0/24
  k3s_args:
  - server
  - --cluster-cidr=10.107.6.0/23
  - --service-cidr=10.107.7.0/23
```

The following `config.yaml` using separate lines and double quotes does work:
```
hostname: k3os071a
k3os:
  environment:
    http_proxy: http://192.168.107.9:8080
    https_proxy: http://192.168.107.9:8080
    no_proxy: localhost,127.0.0.1,192.168.107.0/24
  k3s_args:
  - server
  - "--cluster-cidr"
  - "10.107.4.0/23"
  - "--service-cidr"
  - "10.107.5.0/23"
```

And the following `config.yaml` using separate lines and no quotes does work, and should be documented:
```
hostname: rancher233
k3os:
  environment:
    http_proxy: http://192.168.107.9:8080
    https_proxy: http://192.168.107.9:8080
    no_proxy: localhost,127.0.0.1,192.168.107.0/24
  k3s_args:
  - server
  - --cluster-cidr
  - 10.107.2.0/23
  - --service-cidr
  - 10.107.3.0/23
```

**Additional context**
Thanks to the Rancher folks for clarifying the `k3s_args` options to me.
