### ISSUE TITLE
Running Graphical Applications on K3OS

### ISSUE THREAD

**Issue by gravypod** [rancher/k3os#334]
**Is your feature request related to a problem? Please describe.**
I've been looking at k3os as a possible way to deploy IoT applications. Kubernetes provides a lot of things that people historically over complicate in the development and deployment of IoT hardware. Kubernetes provides:

1. Node authentication (node tokens)
2. Secrets management
3. Storage provisioning
4. Zero-downtime deployments
5. Service discovery
6. Monitoring (metrics-server)

K3OS seems to carry the torch to it's extreme with:

1. Operator-based OS management 
2. Ephemeral disk volume 
3. Light weight

Unfortunately many IoT applications need to display information to a user. For example: a smart thermometer might have a display of the temperature and a touch screen to take in user settings. Some of these displays might use OpenGL/Vulkan while others may use x11 or a full web browser to simply display an SPA. 

Using k3s and k3os as a platform to build any non-user facing IoT system is a no brainier at this point. The only feature I see missing is some way to either run a captive/kiosk browser on the host or run some x11 server that can be passed into a container.

**Describe the solution you'd like**
I'm not sure of the most elegant way to provide this feature set. I see multiple ways forward.

1. Implementing some mechanism for installing software to the host?
2. Demo running x11 inside a docker container on k3os?
3. Decide this is not a feature set that k3os wants to support? 

**Describe alternatives you've considered**

1. Running x11 inside of a docker container and putting all of the IoT GUI stuff in the same pod
2. Building a custom image that installs x11, graphics drivers, etc on the host

**Additional Context**

Most existing IoT offerings essentially offer a watered down feature set of even the most basic kubernetes features. For example [AWS IoT](https://aws.amazon.com/iot/) is a platform basically implementing a locked-in version of a state management and pod scheduler. If something like k3os was polished for this use case I assume many people, who have already bought into the kube ecosystem, would love to use it.

**Comment by dweomer** [comment]
@gravypod I have worked on similar solutions this this space based on LinuxKit and RancherOS using Docker but I haven't yet worked through all of the details necessary to make it work on k3OS. I too would like to have a working customer kiosk style example and I hope to spend some time with that early in the new year.

**Comment by gravypod** [comment]
@dweomer when you get the feature set working I'd be happy to upstream examples and docs for common use cases. Also if you have some design docs and want someone to look over it I'll be watching this issue.

**Comment by gravypod** [comment]
Also as a side note, #64 is likely related. This can probably be achieved via connman since it supports openvpn but this might be a little limiting.

**Comment by gnoejuan** [comment]
Just fyi, I was looking into k3os as a kiosk base too. 

This seems to be a solution for now: https://unix.stackexchange.com/questions/70931/how-to-install-x11-on-my-own-linux-buildroot-system

**Comment by thomas-riccardi** [comment]
FYI balena.io worked a lot on graphics displays from docker:
here is a X11 server + chromium: https://github.com/balenablocks/browser
- they support Intel NUC (even with hardware acceleration)
- it works with `privileged: true` (ideally it should be avoidable/limited, maybe with https://gitlab.com/arm-research/smarter/smarter-device-manager ?)
<details><summary>kubernetes manifest</summary>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tv
  labels:
    app: tv
spec:
  replicas: 1
  serviceName: tv
  selector:
    matchLabels:
      app: tv
  template:
    metadata:
      labels:
        app: tv
    spec:
      containers:
        - name: tv
          image: balenablocks/browser
          env:
            - name: LAUNCH_URL
              value: https://k3os.io/
            - name: KIOSK
              value: '1'
            - name: ENABLE_GPU
              value: '1'
          securityContext:
            privileged: true
```

</details>
