### ISSUE TITLE
k3os 0.8 is not properly working

### ISSUE THREAD

**Issue by stevefan1999-personal** [rancher/k3os#336]
**Version**
0.8.0

**Architecture**
x86_64

**Describe the bug**
supervise-daemon for some reason cannot seems to run k3s from '/sbin'

**To Reproduce**
1. find whatever vm with existing linux install
2. use takeover install
3. reboot
4. fucked up

**Expected behavior**
k3s server should start

**Actual behavior**
k3s server stuck in a start loop

**Additional context**

```
instance-1 [~]# cat /var/log/k3s-service.log
...
 * supervise-daemon: failed to exec `/sbin/k3s': No such file or directory
 * supervise-daemon: Please increase the value of --respawn-period to more than 50 to avoid infinite respawning
...
instance-1 [~]# /sbin/k3s
NAME:
   k3s - Kubernetes, but small and simple

USAGE:
   k3s [global options] command [command options] [arguments...]

VERSION:
   v1.0.0 (18bd921c)

COMMANDS:
   server        Run management server
   agent         Run node agent
   kubectl       Run kubectl
   crictl        Run crictl
   ctr           Run ctr
   check-config  Run config check
   help, h       Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug        Turn on debug logs [$K3S_DEBUG]
   --help, -h     show help
   --version, -v  print the version
instance-1 [~]#
```
Houston we have a problem.

Config is fine, can be accessed via /k3os/system/config.yaml.
This is my config:
```yml
---
hostname: k3os-master-gcp-0
k3os:
  k3s_args:
    - server
  server_url: "https://<REDACTED>:6443"
  token: "attack at dawn"
ssh_authorized_keys:
  - ssh-ed25519 <REDACTED>
  - <REDACTED>
```
