### ISSUE TITLE
write_files not working under certain circumstances

### ISSUE THREAD

**Issue by joharper54SEG** [rancher/k3os#357]
**Version**
v0.8.0

**Architecture**
x86_64

**Describe the bug**
I have a config.yaml file that I am embedding into the ISO we use to image devices.  In this config.yaml I have the below write_files that creates a script to execute on run_cmd.  It then contacts a web server and pulls the location-specific config.yaml that should be applied after each reboot.  This was working fine until I used write_files in the location-specific.yaml file to set a static IP.  Now when imaging runs, I see the INFO messages that all the files are being created and downloaded.  But after a reboot the device comes up missing all the files that were created.  There is an error on boot that it failed to run config.sh during run_cmd.  This is due to the file not being there.  If I comment out the write_files section in the location-specific.yaml file and re-image, everything works again.

```yaml
#embedded on ISO
write_files:
  - encoding: ""
    content: ""
    owner: rancher
    path: /home/rancher/location
    permissions: '0644'
  - encoding: ""
    content: |-
        #!/bin/bash
        let "location = some math to determine location by subnet"
        sudo wget https://URL/$location/$location.yaml -O /var/lib/rancher/k3os/config.yaml
    owner: rancher
    path: /home/rancher/config.sh
    permissions: '0755'
run_cmd:
- sudo bash /home/rancher/config.sh
```

```yaml
#location specific yaml
ssh_authorized_keys:
- ssh-rsa AAA...
hostname: hostname
write_files:
  - enconding: ""
    content: |-
      [service_ethernet]
      Type = ethernet
      IPv4 = 192.168.250/255.255.255.0/192.168.1.1
      IPv6 = off
      Nameservers = 192.168.1.1
      SearchDomains = domain.com
      Timeservers = 192.168.1.1
      Domain = domain.com
    owner: rancher
    path: /var/lib/connman/location.config
    permissions: '0755'
```

**Comment by dweomer** [comment]
@joharper54SEG are you able to provide the boot/console log? Specifically I would like to see the snippets where the `ccapply` openrc service emits the error(s).

**Comment by dweomer** [comment]
@joharper54SEG additionally, the `write_files` for the ISO `config.yaml` is writing to `/var/lib/rancher/k3os/config.yaml` explicitly which is normally fine so long as there isn't a `config.yaml` in that location already. An overwrite will probably get you unexpected behavior. To prevent accidental overwrite consider changing your script your script to pull down the location-specific config and place it in the config drop-in directory, i.e.`/var/lib/rancher/k3os/config.d/location.yaml`.

**Comment by joharper54SEG** [comment]
Is there a boot/console log written to disk somewhere?  If not, ill see if I can record the boot process and screenshot the relevant sections.

**Comment by joharper54SEG** [comment]
boot from ISO
![image](https://user-images.githubusercontent.com/46793278/72943240-916a7e00-3d43-11ea-9f47-71289d13faab.png)
![image](https://user-images.githubusercontent.com/46793278/72943456-18b7f180-3d44-11ea-9352-5330eb2034c3.png)

Boot from disk after imaging
![image](https://user-images.githubusercontent.com/46793278/72943523-44d37280-3d44-11ea-85d2-7e14d87f052b.png)
![image](https://user-images.githubusercontent.com/46793278/72943550-51f06180-3d44-11ea-86cc-32583abdcd06.png)

**Comment by dweomer** [comment]
@joharper54SEG what is happening here is that the `write_files` from the location-specific `config.yaml` is overriding the `write_files` from the `config.yaml` from the ISO. This is because when  k3OS parses config files in this order
- `/k3os/system/config.yaml`
- `/var/lib/rancher/k3os/config.yaml`
- `/var/lib/rancher/k3os/config.d/*`

the last occurrence of any top-level element encountered overwrites what was there before.

To better demonstrate what I am talking about, I've synthesized a representative example from your provided snippets. Booting from ISO with the following `/k3os/config/config.yaml`:
```yaml
write_files:
  - encoding: ""
    content: |-
      #!/bin/bash
      cat << EOF > /var/lib/rancher/k3os/config.yaml
      ssh_authorized_keys:
        - github:dweomer
      write_files:
        - encoding: ""
          content: |-
            #!/bin/bash
            ip -json addr show eth0 | jq -r . > /run/k3os/eth0.json
            cat /run/k3os/eth0.json
          owner: rancher
          path: /home/rancher/location.sh
          permissions: '0755'
      run_cmd:
        - /home/rancher/location.sh
      EOF
    owner: rancher
    path: /home/rancher/config.sh
    permissions: '0755'
init_cmd:
  - uname -a # this will show up both when booting from ISO and after installation
boot_cmd:
  - /home/rancher/config.sh # no need for `sudo bash ...` because it was written with 0755 perms
```
... and then invoking `sudo k3os config --dump`:
```yaml
boot_cmd:
- /home/rancher/config.sh
init_cmd:
- uname -a
k3os: {}
run_cmd:
- /home/rancher/location.sh
ssh_authorized_keys:
- github:dweomer
write_files:
- content: |-
    #!/bin/bash
    ip -json addr show eth0 | jq -r . > /run/k3os/eth0.json
    cat /run/k3os/eth0.json
  encoding: ""
  owner: rancher
  path: /home/rancher/location.sh
  permissions: "0755"
```
Notice that `init_cmd` and `boot_cmd` are present from the initial config but that the `write_files` has been overridden. **This is the config that `sudo k3os install` will drop at `/k3os/system/config.yaml` unless you specify a config URL**
