### ISSUE TITLE
Support 2G/3G/4G Modem Connectivity

### ISSUE THREAD

**Issue by janeczku** [rancher/k3os#400]
Thanks for helping us to improve k3OS! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
We want to run k3os on field deployable devices that are using mobile network for connectivity.

**Describe the solution you'd like**
We would like to be able to attach 3G USB dongles or PCI Cards and configure the PPP interface via the k3os config.yaml such like:

```
k3os:
  wwan:
  - interface: wwan0
    apn: pinternet.telekom.de
    init: AT+CGDCONT=1,"IP"
```
