### ISSUE TITLE
manifests/traefik.yaml immune to write_files

### ISSUE THREAD

**Issue by hughobrien** [rancher/k3os#424]
k3os version v0.9.1
5.0.0-37-generic #40~18.04.1 SMP Wed Jan 15 04:09:29 UTC 2020
x86_64

The write_files config cannot be used to set `/var/lib/rancher/k3s/server/manifests/traefik.yaml`

The file remains in its default state.

```
write_files:
- path: /var/lib/rancher/k3s/server/manifests/traefik.yaml
  content: |
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: traefik
      namespace: kube-system
    spec:
      chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
      set:
        rbac.enabled: "true"
        ssl.enabled: "true"
        metrics.prometheus.enabled: "true"
        kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
        dashboard.enabled: "true"
        dashboard.domain: "traefik.<mydomain>"
        dashboard.ingress.annotations.kubernetes\.io/ingress\.class: "traefik"
        dashboard.ingress.annotations.traefik\.ingress\.kubernetes\.io/redirect-entry-point: "https"
        dashboard.ingress.annotations.cert-manager\.io/cluster-issuer: "letsencrypt"
        dashboard.ingress.tls[0].hosts[0]: "traefik.<mydomain>"
        dashboard.ingress.tls[0].secretName: "traefik-cert"
  owner: root
  permissions: '0600'
  encoding: ""
```

If the file is written manually all is well but it reverts on reboot.

ccapply claims `wrote file /var/lib/rancher/k3s/server/manifests/traefik.yaml to filesystem`

From `/var/log/k3s-service.log` - it looks like it's overwritten on k3s startup.
```
time="2020-04-07T15:58:52.787014161Z" level=info msg="Done waiting for CRD helmcharts.helm.cattle.io to become available"
time="2020-04-07T15:58:52.796156741Z" level=info msg="Writing static file: /var/lib/rancher/k3s/server/static/charts/traefik-1.81.0.tgz"
<snip>
time="2020-04-07T15:58:52.797044245Z" level=info msg="Writing manifest: /var/lib/rancher/k3s/server/manifests/traefik.yaml"
<snip>
time="2020-04-07T15:58:52.898450922Z" level=info msg="Starting k3s.cattle.io/v1, Kind=Addon controller"
time="2020-04-07T15:58:52.899591518Z" level=info msg="Waiting for master node  startup: resource name may not be empty"
time="2020-04-07T15:58:52.898566034Z" level=info msg="Node token is available at /var/lib/rancher/k3s/server/token"
time="2020-04-07T15:58:52.902716376Z" level=info msg="To join node to cluster: k3s agent -s https://10.0.0.2:6443 -t ${NODE_TOKEN}"
2020-04-07 15:58:52.933042 I | http: TLS handshake error from 10.0.0.2:34560: remote error: tls: bad certificate
time="2020-04-07T15:58:52.973959520Z" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
time="2020-04-07T15:58:52.973993910Z" level=info msg="Run: k3s kubectl"
time="2020-04-07T15:58:52.974002758Z" level=info msg="k3s is up and running"
```

A cursory search suggests it's blindly written from here: https://github.com/rancher/k3s/blob/master/pkg/deploy/zz_generated_bindata.go

**Comment by dweomer** [comment]
@hughobrien this is default, expected behavior for k3s. to disable the traefik deployment on k3OS you will need to have something like this for your `config.yaml`:
```yaml
k3os:
  k3s_args:
  - "server"
  - "--no-deploy=traefik"
```
