### ISSUE TITLE
Run phase does not apply some of the configuration options hostname, k3os.password etc..

### ISSUE THREAD

**Issue by brlbil** [rancher/k3os#448]
**Version (k3OS / kernel)**
`k3os version v0.10.0`
`5.0.0-43-generic #47~18.04.1 SMP Wed Apr 1 16:27:01 UTC 2020`

**Architecture**
`x86_64`

**Describe the bug**
According to the [documentation](https://github.com/rancher/k3os#phases) expect init_cmd and boot_cmd every other configuration parameter should be applied in the run phase. But it seems only some of the configuration options are applied during the run phase. Please see the applied configuration parameters in the source file [RunApply](https://github.com/rancher/k3os/blob/master/pkg/cc/apply.go#L27).

**To Reproduce**
Set hostname and k3os.password with a config file and provide the config to the host with a cloud-init method. In my case, I am using cdrom. 

**Expected behavior**
The hostname and rancher user's password is expected to match the configuration.

**Actual behavior**
These and some other config parameters are ignored.

**Additional context**
I have checked the apply.go file's commit history. As far as I can see first ApplyInstall and ApplyK3SInstall were added then only ApplyEnvironment was added. If help needed with a fix I would like to get involved.

**Comment by dweomer** [comment]
@brlbil please share the `config.yaml `You are using

**Comment by brlbil** [comment]
@dweomer config.yaml is down below. I have tried also with the simplified version which has no write_files or run_cmd sections and the result is the same, the hostname and password do not applied but ssh keys are applied.

```
ssh_authorized_keys:
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOCwh9o5FMRkbRMOrn7Jd8WhEF3i+E1cfLfOI+1h58B
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8xZKUnlOYE9+nRHXZDkxrg6X0Lpdt4It86b12YETdy
hostname: cc1
write_files:
- content: |-
    alias ll='ls -alF'
  owner: root
  path: /etc/profile.d/alias.sh
  permissions: '0644'
- enconding: ""
  content: |-
    #!/bin/bash
    write_log () {
        local message="${1}"
        logger -t "run-cmd" "${message}"
        echo "${message}"
    }
    write_log "Getting the service using eth0..."
    ETH0=$(connmanctl services | awk '{ print $3 }' | while read -r s1; do connmanctl services $s1 | grep -q "eth0" && echo "$s1"; done)
    write_log "eth0 is bound to: ${ETH0}"
    write_log "Setting up manual net config..."
    connmanctl config $ETH0 --ipv4 manual 192.168.100.2 255.255.255.0 192.168.100.1 --nameservers 192.168.100.1
    connmanctl config $ETH0 --ipv6 off
    write_log "Restarting connman..."
    service connman restart
    write_log "$(connmanctl services $ETH0)"
    write_log "Network setup done."
  owner: root:root
  path: /etc/run-cmd.sh
  permissions: '0755'
run_cmd:
- "/etc/run-cmd.sh"

k3os:
  ntp_servers:
  - 0.no.pool.ntp.org
  - 1.no.pool.ntp.org
  password: "1q2w3e4r"
  token: kjhfsjdbvhfbasbshdbmahsbdflajbfdvcsd
  k3s_args:
  - server
```

**Comment by dweomer** [comment]
```yaml
ssh_authorized_keys:
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOCwh9o5FMRkbRMOrn7Jd8WhEF3i+E1cfLfOI+1h58B
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8xZKUnlOYE9+nRHXZDkxrg6X0Lpdt4It86b12YETdy
hostname: cc1
```

@brlbil maybe this is a transcription / copy-pasta error but your ssh keys are not properly specified. by way of example, I put your `config.yaml` in a running system so I could use `k3os config --dump` as a verification check, i.e.:

### my /k3os/system/config.yaml as a simple working example
```
nuc-1 [/var/lib/rancher/k3os]$ sudo cat /k3os/system/config.yaml
```
```yaml
hostname: nuc-1

k3os:
  password: rancher
  token: demo
  k3s_args:
  - server

ntp_servers:
- 0.us.pool.ntp.org
- 1.us.pool.ntp.org

run_cmd:
- rc-service ntpd start
- sleep 5

ssh_authorized_keys:
- github:dweomer
```
### verify my /k3os/system/config.yaml
```
nuc-1 [/var/lib/rancher/k3os]$ sudo k3os config --dump
```
```yaml
hostname: nuc-1
k3os:
  k3s_args:
  - server
  password: rancher
  token: demo
run_cmd:
- rc-service ntpd start
- sleep 5
ssh_authorized_keys:
- github:dweomer
```
### add your config.yaml to `/var/lib/rancher/k3os/config.d`
```
nuc-1 [/var/lib/rancher/k3os]$ sudo mv -vf brlbil.yaml config.d/
renamed 'brlbil.yaml' -> 'config.d/brlbil.yaml'
nuc-1 [/var/lib/rancher/k3os]$ cat config.d/brlbil.yaml
```
```yaml
ssh_authorized_keys:
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOCwh9o5FMRkbRMOrn7Jd8WhEF3i+E1cfLfOI+1h58B
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8xZKUnlOYE9+nRHXZDkxrg6X0Lpdt4It86b12YETdy
hostname: cc1
write_files:
- content: |-
    alias ll='ls -alF'
  owner: root
  path: /etc/profile.d/alias.sh
  permissions: '0644'
- enconding: ""
  content: |-
    #!/bin/bash
    write_log () {
        local message="${1}"
        logger -t "run-cmd" "${message}"
        echo "${message}"
    }
    write_log "Getting the service using eth0..."
    ETH0=$(connmanctl services | awk '{ print $3 }' | while read -r s1; do connmanctl services $s1 | grep -q "eth0" && echo "$s1"; done)
    write_log "eth0 is bound to: ${ETH0}"
    write_log "Setting up manual net config..."
    connmanctl config $ETH0 --ipv4 manual 192.168.100.2 255.255.255.0 192.168.100.1 --nameservers 192.168.100.1
    connmanctl config $ETH0 --ipv6 off
    write_log "Restarting connman..."
    service connman restart
    write_log "$(connmanctl services $ETH0)"
    write_log "Network setup done."
  owner: root:root
  path: /etc/run-cmd.sh
  permissions: '0755'
run_cmd:
- "/etc/run-cmd.sh"

k3os:
  ntp_servers:
  - 0.no.pool.ntp.org
  - 1.no.pool.ntp.org
  password: "1q2w3e4r"
  token: kjhfsjdbvhfbasbshdbmahsbdflajbfdvcsd
  k3s_args:
  - server
```

### attempt to verify your config.yaml (merged with mine)
```
nuc-1 [/var/lib/rancher/k3os]$ sudo k3os config --dump
ERRO[0000] error converting YAML to JSON: yaml: line 3: could not find expected ':' 
```

### fix your ssh keys
```
nuc-1 [/var/lib/rancher/k3os]$ head -3 config.d/brlbil.yaml 
```
```yaml
ssh_authorized_keys:
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOCwh9o5FMRkbRMOrn7Jd8WhEF3i+E1cfLfOI+1h58B
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8xZKUnlOYE9+nRHXZDkxrg6X0Lpdt4It86b12YETdy
```
### verify your fixed yaml
```
nuc-1 [/var/lib/rancher/k3os]$ sudo k3os config --dump
```
```yaml
hostname: cc1
k3os:
  k3s_args:
  - server
  ntp_servers:
  - 0.no.pool.ntp.org
  - 1.no.pool.ntp.org
  password: 1q2w3e4r
  token: kjhfsjdbvhfbasbshdbmahsbdflajbfdvcsd
run_cmd:
- /etc/run-cmd.sh
ssh_authorized_keys:
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOCwh9o5FMRkbRMOrn7Jd8WhEF3i+E1cfLfOI+1h58B
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8xZKUnlOYE9+nRHXZDkxrg6X0Lpdt4It86b12YETdy
write_files:
- content: alias ll='ls -alF'
  encoding: ""
  owner: root
  path: /etc/profile.d/alias.sh
  permissions: "0644"
- content: |-
    #!/bin/bash
    write_log () {
        local message="${1}"
        logger -t "run-cmd" "${message}"
        echo "${message}"
    }
    write_log "Getting the service using eth0..."
    ETH0=$(connmanctl services | awk '{ print $3 }' | while read -r s1; do connmanctl services $s1 | grep -q "eth0" && echo "$s1"; done)
    write_log "eth0 is bound to: ${ETH0}"
    write_log "Setting up manual net config..."
    connmanctl config $ETH0 --ipv4 manual 192.168.100.2 255.255.255.0 192.168.100.1 --nameservers 192.168.100.1
    connmanctl config $ETH0 --ipv6 off
    write_log "Restarting connman..."
    service connman restart
    write_log "$(connmanctl services $ETH0)"
    write_log "Network setup done."
  encoding: ""
  owner: root:root
  path: /etc/run-cmd.sh
  permissions: "0755"
```

**Comment by brlbil** [comment]
@dweomer Sorry, as you suspected there was a copy and paste error on my side.
For simplicity, I have removed write_files but the problem is the same as the hostname, password nor NTP servers are not set.

**verify running-config**
`k3os config --dump`
```yaml
k3os config --dump
hostname: cc1
k3os:
  data_sources:
  - cdrom
  - aws
  k3s_args:
  - server
  ntp_servers:
  - 0.no.pool.ntp.org
  - 1.no.pool.ntp.org
  password: 1q2w3e4r
  token: kjhfsjdbvhfbasbshdbmahsbdflajbfdvcsd
ssh_authorized_keys:
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOCwh9o5FMRkbRMOrn7Jd8WhEF3i+E1cfLfOI+1h58B
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8xZKUnlOYE9+nRHXZDkxrg6X0Lpdt4It86b12YETdy
```

The system is configured with /k3os/system/config.yaml and cloud user-data, please find them below.

**/k3os/system/config.yaml**
```yaml
ssh_authorized_keys:
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOCwh9o5FMRkbRMOrn7Jd8WhEF3i+E1cfLfOI+1h58B

k3os:
  data_sources:
  - cdrom
  - aws
  password: "12345"
```

**/run/config/userdata**
```yaml
ssh_authorized_keys:
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOCwh9o5FMRkbRMOrn7Jd8WhEF3i+E1cfLfOI+1h58B
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8xZKUnlOYE9+nRHXZDkxrg6X0Lpdt4It86b12YETdy
hostname: "cc1"

k3os:
  ntp_servers:
  - 0.no.pool.ntp.org
  - 1.no.pool.ntp.org
  password: "1q2w3e4r"
  token: kjhfsjdbvhfbasbshdbmahsbdflajbfdvcsd
  k3s_args:
  - server
```

Below are the files should have changed with this configuration.

**/etc/hostname**
```
k3os-6516
```

**/etc/connman/main.conf**
```
[General]
NetworkInterfaceBlacklist=veth
FallbackNameservers=8.8.8.8
```

I admit I am new to this codebase but I do not think this is nothing to do with the configuration.
I have tried this with a lot of combinations so far. If I am reading the code below correctly run phase configured to apply only these configurations.

[pkg/cc/apply.go](https://github.com/rancher/k3os/blob/master/pkg/cc/apply.go#L27)
```go
func RunApply(cfg *config.CloudConfig) error {
	return runApplies(cfg,
		ApplySSHKeysWithNet,
		ApplyWriteFiles,
		ApplyEnvironment,
		ApplyRuncmd,
		ApplyInstall,
		ApplyK3SInstall,
	)
}
```
