### ISSUE TITLE
k3os internal dqlite HA unstable "failed to create dqlite connection: no available dqlite leader server found"

### ISSUE THREAD

**Issue by k1n6b0b** [rancher/k3os#454]
**Version (k3OS / kernel)**
> k3os version v0.10.0
> 5.0.0-43-generic #47~18.04.1 SMP Wed Apr 1 16:27:01 UTC 2020

**Architecture**
> k3os x86_64

3x hosts:
* k3os-1
* k3os-2
* k3os-3

General cloud-config:
```
hostname: "k3os-1.REDACTED"
k3os:
  data_sources:
  modules:
    - kvm
    - nvme
  sysctl:
    kernel.printk: 4 4 1 7
    kernel.kptr_restrict: 1
  network:
    interfaces:
      eth0:
         dhcp: true
  ntp_servers:
    - ntp.[REDACTED]
  dns_nameservers:
    - xx.xx.xx.xx
  # Rancher User PW
  password: "REDACTED"
  token: "REDACTED"
  labels:
    region: na-us-01
    prupose: testing
  k3s_args:
    - server
    - "-v=3"
    - "--cluster-init"
```
subsequent hosts are joined with `"--server=https://k3os-1.k3s.[REDACTED]:6443"`

**Describe the bug**
I've installed k3os multiple times using the internal HA db and each time have ended up with a corrupted install after deploying rancher.

Error from server: rpc error: code = Unknown desc = failed to create dqlite connection: no available dqlite leader server found

**To Reproduce**

1.  Deploy 3x k3os hosts with --cluster-init on the first, joining the 2nd two to the first
2.  Deploy rancher via helm
```
kubectl.exe create namespace cattle-system
kubectl -n cattle-system create secret generic tls-ca --from-file=cacerts.pem
kubectl -n cattle-system create secret generic tls-ca-additional --from-file=cacerts.pem
kubectl.exe -n cattle-system create secret tls tls-rancher-ingress --cert=rancher.k3s.[REDACTED] --key=ranch
er.k3s.[REDACTED]
helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher.k3s.[REDACTED] --set ingress.tls.source=secret --set privateCA=true --set additionalTrustedCAs=true
```

**Expected behavior**
* Rancher and k3s to stay stable

**Actual behavior**
* Rancher starts and appears to deploy successfully
* Unable to proceed, cluster becomes unstable (tried deploying syslog configs, or making any changes)
* dqlight blows up i think.  See logs
* Reboots of any hosts dont show failover successfully
* All hosts eventually fall into this cannot connect to db state

```
k3os-2 [~]$ kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Error from server: rpc error: code = Unknown desc = failed to create dqlite connection: no available dqlite leader server found
```

```
level=info msg="Starting k3s v1.17.4+k3s1 (3eee8ac3)"
level=info msg="Cluster bootstrap already complete"
level=info msg="Testing connection to peers [10.10.11.13:6443 10.10.11.11:6443 10.10.11.12:6443]"
level=info msg="Connection OK to peers [10.10.11.13:6443 10.10.11.11:6443 10.10.11.12:6443]"
level=error msg="failed to setup db: not an error"
level=error msg="failed to setup db: not an error"
level=error msg="failed to setup db: not an error"
level=error msg="failed to setup db: not an error"
level=error msg="failed to setup db: not an error"
level=error msg="failed to setup db: not an error"
level=error msg="failed to setup db: not an error"
level=error msg="failed to setup db: not an error"
```

**Additional context**
See log files:
[putty-k3os-1.k3s.REDACTED.log](https://github.com/rancher/k3os/files/4578611/putty-k3os-1.k3s.REDACTED.log)
[putty-k3os-2.k3s.REDACTED.log](https://github.com/rancher/k3os/files/4578612/putty-k3os-2.k3s.REDACTED.log)
[putty-k3os-3.k3s.REDACTED.log](https://github.com/rancher/k3os/files/4578613/putty-k3os-3.k3s.REDACTED.log)
