### ISSUE TITLE
K3OS upgrade staging

### ISSUE THREAD

**Issue by joharper54SEG** [rancher/k3os#456]
**Is your feature request related to a problem? Please describe.**
We are planning on running single k3os nodes is some very remote locations that have questionable network links.  When using the upgrade controller, the first step it performs is to cordon the node which takes all the pods down.  It then starts pulling all its upgrades which can take several hours to complete in some locations.  During this time, all services provided by the pods in these locations are down.

Additionally, I don't see any options to schedule when upgrade controller executes, so to plan for this downtime is problematic.

**Describe the solution you'd like**
It would be nice to have a option to stage upgrades so when then upgrade controller executes it does its downloads first before the cordon.

**Describe alternatives you've considered**
An alternative path, for now, would be to use the old upgrade scripts provided pre 0.9.0.  These seem to be much less disruptive for the pods.

**Comment by dweomer** [comment]
With https://github.com/rancher/system-upgrade-controller/pull/61 this can be made to work with a `prepare` container:

```yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3os-latest
  namespace: k3os-system
spec:
  concurrency: 1
  channel: https://github.com/rancher/k3os/releases/latest
  nodeSelector:
    matchExpressions:
      - {key: plan.upgrade.cattle.io/k3os-latest, operator: Exists}
      - {key: k3os.io/mode, operator: Exists}
      - {key: k3os.io/mode, operator: NotIn, values: ["live"]}
  serviceAccountName: k3os-upgrade
  prepare:
    image: rancher/k3os
    command: [k3os, --version]
    args: []
  drain:
    force: true
  upgrade:
    image: rancher/k3os
    command: [k3os, --debug]
    args:
      - upgrade
      - --kernel
      - --rootfs
      - --remount
      - --sync
      - --reboot
      - --lock-file=/host/run/k3os/upgrade.lock
      - --source=/k3os/system
      - --destination=/host/k3os/system
```

This is the default plan with:
