### ISSUE TITLE
Update documentation with example of bonding NICs.

### ISSUE THREAD

**Issue by neerdoc** [rancher/k3os#457]
For setups with multiple NICs it is nice to be able to use bonding (like LACP) to utilize all NICs for speed and/or redundancy.

I've managed to set that up with the help of @dweomer in my system. The only thing that was actually needed was some setup in the `config.yaml` file. For details about the commands, please see the [ Linux Ethernet Bonding Driver HOWTO ](https://www.cyberciti.biz/howto/question/static/linux-ethernet-bonding-driver-howto.php), especially section 3.3.

To let other people find the solution more easily, I would like to update the documentation (e.g., the README.md) file with an example on how to achieve this.

This is what worked for me:

- To activate the `bonding` kernel module I added:
```
k3os:
  modules:
    - bonding mode=4 miimon=100 lacp_rate=1
```
- Then I generated a script that sets up the bond:
```
write_files:
  - content: |
      ifenslave bond0 eth0
      ifenslave bond0 eth1
      ifenslave bond0 eth2
      ifenslave bond0 eth3
      ifconfig bond0 192.168.1.10 netmask 255.255.255.0 up hw ether xx:xx:xx:xx:xx:xx
      rc-service issue restart
    owner: root:root
    path: /etc/bonding
    permissions: '0755'
```
_Note 1_: The `rc-service issue restart` is not strictly necessary but updates the login prompt to find the bond.
_Note 2_: The `ifconfig` command must come last only if you need to set the MAC-address. If `hw ether xx:xx:xx:xx:xx:xx` is skipped or ran _before_ the `ifenslave` commands the MAC-address of the bond will be that of the first NIC that comes online, i.e., random of the NICs included in the bond.
- Finally the script must be executed at runtime:
```
run_cmd:
  - /etc/bonding
```

**Comment by brunnels** [comment]
I've been working with this and had issues because unconfigured ntp, domain, dns, search domains, etc...

I was able to fix it and everything works perfectly now and shows to be correctly configured when doing `sudo connmanctl services ethernet_b8ca3a664ece_cable`

Here's my config.  The most important part is that the MAC address in `MAC = B8:CA:3A:66:4E:CE` matches `ifconfig bond0 up hw ether B8:CA:3A:66:4E:CE` because connman does it's matching on the MAC address.

I also included my solution to getting nfs setup properly to support nfs persistent volumes.

```yaml
---
hostname: k3s-node1
write_files:
- content: |-
    [service_eth]
    Type = ethernet
    IPv4 = off
    IPv6 = off
    
    [service_bond0]
    Type = ethernet
    DeviceName = bond0
    IPv4 = 192.168.0.14/255.255.255.0/192.168.0.254
    IPv6 = off
    Nameservers = 192.168.0.254
    Timeservers = 0.us.pool.ntp.org,1.us.pool.ntp.org
    Domain = lan.domain.com
    SearchDomains = lan.domain.com,cloud.domain.com,domain.com
    MAC = B8:CA:3A:66:4E:CE
    
  path: /var/lib/connman/default.config
  owner: root
  permissions: '0644'

run_cmd:
- ifenslave bond0 eth0
- ifenslave bond0 eth1
- ifenslave bond0 eth2
- ifenslave bond0 eth3
- ifenslave bond0 eth4
- ifconfig bond0 up hw ether B8:CA:3A:66:4E:CE
- sleep 5
- service connman restart

boot_cmd:
- mkdir -p /var/lib/nfs/sm
- rc-update add rpc.statd
- rc-update add nfs

k3os:
  modules:
  - nfs
  - bonding mode=802.3ad miimon=100 lacp_rate=fast
 ```
