### ISSUE TITLE
GlusterFS Support

### ISSUE THREAD

**Issue by FreekingDean** [rancher/k3os#500]
**Is your feature request related to a problem? Please describe.**
I have an existing GlusterFS storage cluster I'd like to mount using the native kubernetes tooling.

**Describe the solution you'd like**
GlusterFS volume driver support.

**Describe alternatives you've considered**
Looking at SMB/CFIS & NFS mounts. But I think mounting using glusters native storage driver would be better?

**Additional context**

**Comment by FreekingDean** [comment]
Here is the example I am following: https://github.com/kubernetes/examples/tree/master/volumes/glusterfs

Heres my actual code Im applying to a k3os cluster
```yaml
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: [node1]
  ports:
  - port: 1
- addresses:
  - ip: [node2]
  ports:
  - port: 1
- addresses:
  - ip: [node3]
  ports:
  - port: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: glusterfs
spec:
  containers:
  - name: glusterfs
    image: nginx
    volumeMounts:
    - mountPath: "/mnt/glusterfs"
      name: glusterfsvol
  volumes:
  - name: glusterfsvol
    glusterfs:
      endpoints: glusterfs-cluster
      path: kube_vol
      readOnly: true
```

This is the error I see from `kubectl describe pod glusterfs`
```
failed to get Plugin from volumeSpec for volume "glusterfsvol" err=no volume plugin matched
```
