### ISSUE TITLE
How to Install Kubernetes Dashboard on k3os

### ISSUE THREAD

**Issue by aanjaneyam** [rancher/k3os#535]
I am absolutely new to kubernetes, k3s or rancher. I have read the guides for k3s and k3os. However, I was a bit confused as how to install the kubernetes dashboard - the graphical user interface on k3os/kubernetes OS. Is the process to install the dashboard on k3os the same as k3s as described in the link below or there is a different process for k3os?

https://rancher.com/docs/k3s/latest/en/installation/kube-dashboard/

On a side note is the kubernetes dashboard the only comprehensive UI available or is there any other better UI providing more features.

**Comment by zimme** [comment]
Using that guide should work just fine on k3os as far as I can tell.

What I've been doing instead though, is creating a folder `kubernetes-dashboard` in `/var/lib/rancher/k3s/server/manifests` which contains the following files. This could be done using the `write_files` directive in the k3os cloud-init config or manually as I do it currently in my home lab.

00-namespace.yml
```yml
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
```
01-kubernetes-dashboard.yml
```yml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: kubernetes-dashboard
spec:
  chart: kubernetes-dashboard
  repo: https://kubernetes.github.io/dashboard
  targetNamespace: kubernetes-dashboard
```
02-kubernetes-dashboard-admin.yml
```yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <username>
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <username>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: <username>
  namespace: kubernetes-dashboard
```
Replace `<username>` with whatever username you want for the admin user.

The helm-controller will now deploy kubernetes-dashboard and then you can access the dashboard using the following commands.

Get the token to use for login. Replace `<username>` in the following command.
```sh
kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep <username> | awk '{print $1}')
```
Start the proxy
```sh
kubectl proxy
```
Open the following link in your browser.
```
http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login
```

As for the question of other UI's for kubernetes, Rancher would be the obvious one 😝 Other than that I think portainer is going to focus on kubernetes going forward but I don't think that is available today.

Maybe k3os could deploy a default webui, however as there are choices and it's not that hard to deploy yourself I'm not sure it should be baked in. However I don't work at rancher so I'll leave that decision ut to them 😄
