### ISSUE TITLE
Cannot update configuration after initial install

### ISSUE THREAD

**Issue by cwoolum** [rancher/k3os#555]
**Version (k3OS / kernel)**

k3os version v0.10.0

5.4.51-v8+ #1327 SMP PREEMPT Thu Jul 23 11:11:34 BST 2020

**Architecture**

aarch64

**Describe the bug**

According to the documentation, `/var/lib/rancher/k3os/config.yaml` is used to define runtime config after initial install. I created the file and added config but it doesn't seem to apply on boot.

**To Reproduce**

1. Create `/var/lib/rancher/k3os/config.yaml`
2. Add a configuration
    ```
    k3os:
      modules:
      - nfs

    boot_cmd:
    - " /etc/init.d/nfs start"
   ```
3. Reboot using `sudo reboot`

**Expected behavior**

On boot, the nfs service should be started

**Actual behavior**

The nfs service is not started. Running `sudo /etc/init.d/nfs start` starts the service correctly.

**Additional context**

**Comment by dweomer** [comment]
@cwoolum as per our slack convo on this, changing the `boot_cmd` start of nfs to a `run_cmd` was not effectual, is that correct? There is a small fix related to this, I think, that was incorporated into the recently released [v0.11.0](https://github.com/rancher/k3os/releases/tag/v0.11.0) that being #547. If you must use v0.10.x the workaround would be to create that directory in a `boot_cmd`/`run_cmd` prior to starting the service.

**Comment by cwoolum** [comment]
I've updated to 0.11.0. I hooked it up to a monitor and don't see the command being run at all. I tried to add an `echo` to debug but it's not appearing in the logs.

```
run_cmd:
- echo 'Starting NFS Service' && /etc/init.d/nfs start
```

**Comment by dweomer** [comment]
AFAIK `run_cmd` is working, in general, but there may be something that I have overlooked causing your specific case to fail.
Some things to consider:
- To verify that `run_cmd` / `boot_cmd` is working you can always mutate the system with something like `date > /run/date`.
- These are run serially and it is possible that an earlier non-zero exit code is prevent later commands from being executed.

Please verify that `sudo k3os config --dump` returns without error and if you can please share the output here so that I may attempt to replicate what is blocking success for you.

**Comment by cwoolum** [comment]
I was able to log a bit more and it is failing when trying to start the service.

Here is my compiled config.

```yaml
boot_cmd:
- echo "boot_cmd works" >> /tmp/boot_cmd
- mount /dev/sda /mnt/ssd/
- exportfs -r
hostname: k3s-1
k3os:
  dns_nameservers:
  - 192.168.86.1
  - 8.8.8.8
  - 1.1.1.1
  k3s_args:
  - server
  - --cluster-init
  - --disable=traefik,servicelb
  labels:
    plan.upgrade.cattle.io/k3os-latest: yay
  modules:
  - nfs
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
run_cmd:
- echo "before run_cmd works" >> /tmp/run_cmd
- echo 'Starting NFS Service' && sudo service nfs start
- echo "run_cmd works" >> /tmp/run_cmd
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDQDpd5txbgGj8bQj0IpmI2gSaRup9kI2A549IevL8rzE/2RZtN4haDZaQBBi4tHLX3aPd0A9ECXm+BDh5xWkNq9ziXqWDbKhP0az55USOyhZUSrP4bTOO/mkfIqy5B2dIIZCEXERFM5WELy423SyBoaaGgOwCKuP3dpOcFpno1Pm4YhVYClb/jG9YPX+XAAXuGbJ2dydAPa5X68LpqenOXv7iXe0BMOqG1dLlImETNB5BWlHJUdkzMyDrqszCllgRrse92rVKq2V94FOVtwv67BMq5Re4M9hmhUhnacCrwT85yQ3qkT3gkZw02/KISZndxwWLaATRBi9olDFsf6wu6HaW389XbhzyNEjUn2XfqaEDCfBP9om7+oEyOpKAWVLasQ4tOCtmJ3eVQvcZ0IUvtg2tqYGqn5JC9pgEloDTlZ1fjRMjHr6Z6Bx0L/qn+nRmkuZByksJDcYZP61CfTx7QJY2zFSGIkBMTl+fnmJmwsFtXZY+43htZABQAoee83EMEp/NhwpTnR2sU6d2PCLOMU2azibAS7/OYUadnAB4qfBjRYxagzLttjMbNbAXpqKEqPzf+KGcOqVA3BWs8cUEPKWgXfLUc3clwzuOo/xNYFF/oQql+ZzJJtxLNHPo9wahIjqdCVtl7XWxsbGBMmLOinA0RVOFKF2rpDDWEB0PNw==
write_files:
- content: |
    /mnt/ssd 192.168.50.0/16(rw,sync)
  encoding: ""
  owner: ""
  path: /etc/exports
  permissions: ""
```

boot_cmd is running correctly and the first echo to `/tmp/run_cmd` is working as well but the second echo is missing so I assume it's failing to start the service.
