### ISSUE TITLE
Overriding the installed K3os Configuration does not update hostname or password

### ISSUE THREAD

**Issue by philipsparrow** [rancher/k3os#560]
**Version (k3OS / kernel)**
v0.10.3
5.0.0-43-generic #47~18.04.1 SMP Wed Apr 1 16:27:01 UTC 2020

**Architecture**
x86_64

**Describe the bug**
Overriding K3OS configuration values does not work (for `hostname`, `k3os.password`, maybe others).
The values installed to `/k3os/system/config.yaml` are overridden by `cloud-init` but aren't actually modified in the running system.

**To Reproduce**
Install K3OS to a VM using this `cloud-init` config file:
```
k3os:
  password: defaultpassword
  data_sources:
  - cdrom
```
Provide the rest of the configuration in an ISO (filename `config`):
```
#cloud-config
write_files:
- path: /var/lib/connman/default.config
  encoding: ''
  owner: root
  permissions: '0666'
  content: |-
    [service_eth0]
    Type=ethernet
    IPv4=10.1.2.160/255.255.255.0/10.1.2.1
    Nameservers=10.1.2.1,8.8.8.8
    SearchDomains=my.lab
    Domain=my.lab
    IPv6=off
    Timeservers=0.us.pool.ntp.org,1.us.pool.ntp.org
boot_cmd: []
hostname: myhostname
init_cmd: []
run_cmd: []
k3os:
  data_sources:
  - cdrom
  environment: {}
  k3s_args:
  - server
  - --no-deploy=traefik
  - --cluster-cidr=10.42.0.0/16
  - --service-cidr=10.43.0.0/16
  - --cluster-dns=10.43.0.10
  - --cluster-domain=cluster.local
  - --node-name=myhostname
  modules:
  - kvm
  - nvme
  password: newpassword
  token: tE9A2RcNxLbQhNjNS97cRxyq
```

**Expected behavior**
User `rancher` password should be `newpassword`, `hostname` on `bash` prompt should be `myhostname` and also in `/var/lib/rancher/k3os/hostname` and `/etc/hostname` after bootup

**Actual behavior**
`k3os config --dump` shows the correct configuration, however my hostname is `k3os-1234` and the `rancher` user's password is `defaultpassword`.

**Additional context**
Running on vSphere, mounting `cloud-init` configuration as an ISO containing the above file (created using `mkisofs -input-charset utf-8 -o my_config.iso config` where `config` is the file containing my cloud-config YAML).
Presumably if the hostname is missing on boot, somewhere before `cloud-init` is run, the hostname is autogenerated and then not updated after the fact. I am attempting to work around the hostname issue by including:
```
write_files:
- path: /var/lib/rancher/k3os/hostname
  encoding: ''
  owner: root
  permissions: '0666'
  content: |-
    myhostname
- path: /etc/hostname
  encoding: ''
  owner: root
  permissions: '0666'
  content: |-
    myhostname
```
But that doesn't update the bash prompt.
I have provided static network configuration since hostnames can be pushed down by DHCP and that may provide misleading results.
