### ISSUE TITLE
Networking doesn't work after takeover on digital ocean

### ISSUE THREAD

**Issue by fkautz** [rancher/k3os#565]
**Version (k3OS / kernel)**
k3OS v0.11.0
Kernel 5.4.0-37-generic on x86_64 (/dev/tty1)

**Architecture**
Inaccessible

**Describe the bug**
After a takeover, the network is unavailable. There is also no login available (rancher default login fails). eth0 is created and set to UP to a non-routable address (fe00::b49c:78ff:fee9:c33/64 in the test system)

**To Reproduce**
Run takeover on a digital ocean ubuntu image

**Expected behavior**
Networking to work.

**Actual behavior**
Takeover is successful except for networking. Looks like dhcp isn't running?

**Comment by fkautz** [comment]
I'm thinking DO doesn't rely on DHCP. It's probably provided by a cloud-init or other out of band mechanism.

**Comment by fkautz** [comment]
cloud-init starts netplan

cloud-init:
```yaml
   network:
     renderers: ['netplan', 'eni', 'sysconfig']
```

netplan:
```yaml
network:
    version: 2
    ethernets:
        eth0:
            addresses:
            - 167.99.104.246/20
            - 2604:A880:0002:00D0:0000:0000:060B:3001/64
            - 10.46.0.5/16
            gateway4: 167.99.96.1
            gateway6: 2604:a880:0002:00d0:0000:0000:0000:0001
            match:
                macaddress: 12:13:9c:6c:a2:20
            nameservers:
                addresses:
                - 67.207.67.3
                - 67.207.67.2
                search: []
            set-name: eth0
```
