### ISSUE TITLE
Allow late initialization & role change from metadata service

### ISSUE THREAD

**Issue by stevefan1999-personal** [rancher/k3os#568]
**Is your feature request related to a problem? Please describe.**
I cannot change the daemon type in k3os-service because it is fixated in installation time, so the data obtained from data sources and the args are rendered useless. 

**Describe the solution you'd like**
Allow late supervisor daemon file generation, or be refreshed if we can get something from metadata service

**Describe alternatives you've considered**
Create a template image on the cloud server and then get over it with scaling groups.

**Additional context**
Uh, so I ran k3os on multiple free cloud providers and here's a problem: I can't just make two images for agent and server separately. I operates on 5 different cloud providers, and because having to upload two images will probably incur additional fee, so I just want to upload one image for all and then if I want to buy a big node as the master, I can just create it easily from the base image on-the-fly through the use of cloud-init metadata.

I have remastered the ISO with the following `/k3os/system/config.yaml`:
```yaml
--- 
k3os: 
  modules:
    - wireguard
  data_sources:
    - aws
    - gcp
    - oracle
    - alicloud
    - azure # don't worry these three new entries are in PR by me, so wait until linuxkit merge it
ssh_authorized_keys: 
  - "ssh-ed25519 <REDACTED>"
  - "github:stevefan1999-personal"
```
and this as my runtime metadata:
```yaml
--- 
k3os: 
  k3s_args:
    - agent
  sysctl:
    kernel.printk: 4 4 1 7
    kernel.kptr_restrict: 1
  server_url: "https://my.master.awake:6443"
  token: "ATTACK AT DAWN"
  labels:
    type: burstable
    region: united-states
```

But for some reason the config obtained from `/run/config/userdata` does not have any effect afterwards and my instance is always started as k3os server rather than agent, unless I specified agent in k3s_args first. This sounds oxymoronic to me since I thought it should be in an undefined state. I confirmed this by checking the supervisor daemon file. 

This is very frustrating but I don't consider it as a bug, since I really didn't specify any role to begin with. So I suggest if `/k3os/system/config.yaml` does not contain any role information we will wait until more sources are available, and then kernel panic if no role can be determined/undefined/contradictory.
