### ISSUE TITLE
Configuration, k3s params erroring cloud-init

### ISSUE THREAD

**Issue by DarkBlaez** [rancher/k3os#574]
I've tried to stay up on the supported cloud-init options, including when they have evolved from prior versions causing issues. Please convey to me what is the correct format
```yaml
k3os:
  k3s_args:
  - server
  - “--cluster-cidr 10.44.0.0/16"
  - “--service-cidr 10.45.0.0/16"
  - “--cluster-dns= 0.44.0.10”
  - "--no-deploy=traefik”
```
I want to set the cluster IP ranges. I have tried the k3s format, I have even gone so far as to layer on an = , yet it still errors on boot. I am assuming these would go in the k3s_args since that is what they are. Please advise

Thanks
DB

**Comment by dweomer** [comment]
@DarkBlaez as per the docs at https://github.com/rancher/k3os/blob/master/README.md#k3osk3s_args this is a tricky area of the config and easy to get wrong. Please try this config:
```yaml
k3os:
  k3s_args:
  - server
  - “--cluster-cidr=10.44.0.0/16"
  - “--service-cidr=10.45.0.0/16"
  - “--cluster-dns=10.44.0.10”
  - "--no-deploy=traefik”
```

**Comment by DarkBlaez** [comment]
Thanks. I did try that and it still errors out with the standard "error converting yaml to json: line X: did not find expected key" Seems one of the items is not supported

**Comment by DarkBlaez** [comment]
I have even tried this format which was documented
# K3s flags with values in following entry
k3os:
  k3s_args:
  - server
  - "--cluster-cidr"
  - "10.107.0.0/23"
  - "--service-cidr"
  - "10.107.1.0/23"

This has totally stopped progress. I will say thus far most of my issues posted have already been around the options not functioning as per documentation

**Comment by DarkBlaez** [comment]
After verification and trying what is documented, I am concluding that k3os is still incomplete and has not implemented the options pertaining to k3s. Indeed if k3os is to expand it's footprint it will need to address these particular options to allow for multi-cluster operation and exchange. The only thing that has trampled my installs constantly over the course of k3os evolution are the configuration options that either have changed format with the versions or omitted implementation. I challenge someone to double check this

**Comment by dweomer** [comment]
> Thanks. I did try that and it still errors out with the standard "error converting yaml to json: line X: did not find expected key" Seems one of the items is not supported. It's these little errors that can drive one insane since they prevent appropriate cluster boot

@DarkBlaez I am sorry that this is not working for you. If you have the time, please try running the following command on your k3os system after install and sharing the output here:
```shell
sudo k3os config --dump
```
On my homelab cluster server, mine looks like this:
```yaml
hostname: nuc-1
k3os:
  k3s_args:
  - server
  - --no-deploy=servicelb
  modules:
  - configs
  password: rancher
  token: demo
run_cmd:
- rc-service ntpd start
- sleep 5
ssh_authorized_keys:
- github:dweomer
write_files:
- content: |-
    mirrors:
      dweomer.io:
        endpoint:
        - "http://192.168.1.238:80"
    configs:
      dweomer.io: {}
  encoding: ""
  owner: ""
  path: /etc/rancher/k3s/registries.yaml
  permissions: ""
```
