### ISSUE TITLE
merge process for config.yaml

### ISSUE THREAD

**Issue by gbarton** [rancher/k3os#575]
We are seeking a little clarification on the merge process for the config.yaml files.

The docs list 3 locations with my short description:

```bash
/k3os/system/config.yaml # initial install time config.yaml, never changes
/var/lib/rancher/k3os/config.yaml # mod all you want
/var/lib/rancher/k3os/config.d/* # mod as many files as you want
```

The behavior isn't quite like I expect through, if I have this in my /k3os/system/config.yaml:

```yaml
# host configs
write_files:
- encoding: ""
  content: |-
    -----BEGIN CERTIFICATE-----
<---SNIP-->
    -----END RSA PRIVATE KEY-----
  owner: root
  path: /var/lib/rancher/k3s/server/tls/request-header-ca.key
  permissions: '0600'
run_cmd:
- "date &> /tmp/s.out"
k3os:                                                               
  data_sources:                                                     
  - aws                                                             
  k3s_args:                                                         
  - server                                                        
  - "--no-deploy=traefik" 
```

/var/lib/rancher/k3os/config.d/db.yaml:
```yaml
write_files:
- encoding: ""
  content: |-
    #!/bin/bash
    # something usefull
  owner: root
  path:/etc/foo
  permissions: '0644'
k3os:
  k3s_args:
  - server
  - "--datastore-endpoint=(valid url)"
```

/var/lib/rancher/k3os/config.d/registry.yaml:
```yaml
write_files:
- encoding: ""
  content: |-
    <--- valid registries.yaml file --->
  owner: root
  path:/var/lib/rancher/k3s/registries.yaml
  permissions: '0644'
k3os:
  k3s_args:
  - server
  - "--private-registry=/var/lib/rancher/k3s/registries.yaml"
```

I would expect a combined file something along the lines of:

```yaml
# host configs
write_files:
- encoding: ""
  content: |-
    #!/bin/bash
    # something usefull
  owner: root
  path:/etc/foo
  permissions: '0644'
- encoding: ""
  content: |-
    -----BEGIN CERTIFICATE-----
<---SNIP-->
    -----END RSA PRIVATE KEY-----
  owner: root
  path: /var/lib/rancher/k3s/server/tls/request-header-ca.key
  permissions: '0600'
- encoding: ""
  content: |-
    <--- valid registries.yaml file --->
  owner: root
  path:/var/lib/rancher/k3s/registries.yaml
  permissions: '0644'
run_cmd:
- "date &> /tmp/s.out"
k3os:                                                               
  data_sources:                                                     
  - aws                                                             
  k3s_args:                                                         
  - server                                                        
  - "--no-deploy=traefik"
  - "--datastore-endpoint=(valid url)"
  - "--private-registry=/var/lib/rancher/k3s/registries.yaml"
```

But it doesn't come out like that, using the `sudo k3os config --dump` command I would instead see:

```yaml
# host configs
write_files:
- encoding: ""
  content: |-
    <--- valid registries.yaml file --->
  owner: root
  path:/var/lib/rancher/k3s/registries.yaml
  permissions: '0644'
k3os:                                                               
  data_sources:                                                     
  - aws                                                             
  k3s_args:                                                         
  - server                                                        
  - "--private-registry=/var/lib/rancher/k3s/registries.yaml"
```

So a couple of questions:

It looks like the initial config.yaml is ignored when it comes to the config merge, is this true?  I dont see any of my things like run_cmd showing up in the new config.

When combining files, it looks like sections overwrite vs merge?  So my db.yaml was completely ignored because there was a write_files and k3os section in registries.yaml?

I am trying to build a base cluster image that I can use to attach to one of our many clusters.  There is a lot of configuration I need to do at launch time (database, registries, certs, etc) that are unique to the clusters and thus not baked into the build.  My current assumption is that I have a single file available for runtime configuration, and if I need anything from the original `/k3os/system/config.yaml` to persist (eg a write_file) I must duplicate it into this runtime file.  Is this correct?

Thank you for an awesome lightweight OS!
