### ISSUE TITLE
K3os highmemory usage in virtualised environment 

### ISSUE THREAD

**Issue by LordChunk** [rancher/k3os#611]
**Version (k3OS / kernel)**
K3OS: v0.11.1
Kernel: 5.4.0-48-generic # 52 SMP Sat Sep 26 08:27:15 UTC 2020

**Architecture**

x86_64

**Describe the bug**

When I run K3os in KVM or Hyper-V, the hypervisors seem to measure a significantly higher memory usage than what Rancher's internal resource dashboards show. I've tried running them in both Proxmox and Hyper-V, but the issue seems to persist. It seems to be especially bad when I deploy a large number of containers.

Even when these containers should not use much memory, they still seem to make the hypervisor allocate a significant chunk of extra memory to the VM.

I've tried to use the following configurations with and without the part commented out, but that does not seem to make a difference. 
```
#cloud-config
ssh_authorized_keys:
- "github:lordchunk"
boot_cmd:
- "echo Europe/Amsterdam > /etc/timezone"
k3os:
  # modules:
  # - kvm
  ntp_servers:
  - 0.nl.pool.ntp.org
  - 1.nl.pool.ntp.org
  - 2.nl.pool.ntp.org
  - 3.nl.pool.ntp.org
  dns_nameservers:
  - 1.1.1.1
  - 1.0.0.1
  k3s_args:
  - "--disable=traefik"
```

**To Reproduce**

**Expected behaviour**

The hypervisor and Rancher dashboard display similar memory usage.

**Actual behaviour**

Hypervisors observe significantly higher memory usage than Rancher's dashboard shows.

**Additional context**

For clarification, this is what I mean with Rancher's dashboard.
![image](https://user-images.githubusercontent.com/23651869/99604296-686b5600-2a05-11eb-92a0-102789164521.png)

This was the memory usage at the same moment as the other screenshot.
![image](https://user-images.githubusercontent.com/23651869/99604340-86d15180-2a05-11eb-8117-975e62bdfe99.png)

I understand that the differences shown in the screenshot may be within a margin of error, but the gap grows with the amount of memory that is used.
