### ISSUE TITLE
After a complete power off: the server is currently unable to handle the request 

### ISSUE THREAD

**Issue by dharmendrakariya** [rancher/k3os#613]
**Version (k3OS / kernel)**

Node1 OS/kernel ========== 5.9.8-2-MANJARO Linux  ( k3s version v1.19.3+k3s3 (0e4fbfef) )
Node2/3 k3os --version ========= k3os version v0.19.2-dev.4

**Architecture**

Node1/2/3 ==== x86_64

**Describe the bug**

Hi, I am creating 3 node HA cluster with embedded db option. I am having 3 nodes, Node1 is running on my system having k3s installed and running the --cluster-init command. Node2 and Node3 are k3os and I am using configs

# Node2 CloudInit

```
ssh_authorized_keys:
- ssh-ed25519 hdjkldhkd... (either rsa or ssh-ed will be fine)
- "github:YourGithubUserName" (this will be used to fetch public key stored in your github account and it will be placed under ssh/authorised_keys in Node2/3)
k3os:
  data_sources:
  - aws
  - cdrom
  modules:
  - kvm
  - nvme
  sysctl:
    kernel.printk: "4 4 1 7"
    kernel.kptr_restrict: "1"
  dns_nameservers:
  - 192.168.1.1 (if you have your own DNS configured)
  - 8.8.8.8
  ntp_servers:
  - 0.in.pool.ntp.org
  - 1.in.pool.ntp.org
  server_url: https://192.168.1.X:6443  (IP of Node1)
  token: secrets
 
  k3s_args:
  - server
  - "--node-name=node2"
 
```

# Node3 CloudInit

```
ssh_authorized_keys:
- ssh-ed25519 hdjkldhkd... (either rsa or ssh-ed will be fine)
- "github:YourGithubUserName" (this will be used to fetch public key stored in your github account and it will be placed under ssh/authorised_keys in Node2/3)
k3os:
  data_sources:
  - aws
  - cdrom
  modules:
  - kvm
  - nvme
  sysctl:
    kernel.printk: "4 4 1 7"
    kernel.kptr_restrict: "1"
  dns_nameservers:
  - 192.168.1.1 (if you have your own DNS configured)
  - 8.8.8.8
  ntp_servers:
  - 0.in.pool.ntp.org
  - 1.in.pool.ntp.org
  server_url: https://192.168.1.X:6443  (IP of Node1)
  token: secrets
 
  k3s_args:
  - server
  - "--node-name=node3"
 
```

HA cluster comes up fine in the first try but after reboot it is giving the error and behaving like [this same issue](https://github.com/rancher/k3s/issues/2249)

**To Reproduce**

Have 3 nodes, Node1 running k3s on manjaro (or I guess any os), Node2 and Node3 bootstrapped with cloudinit files given above.
after successful HACluster comes up, try to reboot the whole architecture systems, its giving the stated error and cluster is not re-created(formed).
 

**Expected behavior**

cluster should come up.

**Actual behavior**

cluster giving error "the server is currently unable to handle the request"

**Additional context**

relevant issue [from k3s](https://github.com/rancher/k3s/issues/2249)
