### ISSUE TITLE
cloud-init: Could not unmarshall userdata: invalid character '#'

### ISSUE THREAD

**Issue by tobru** [rancher/k3os#619]
**Version (k3OS / kernel)**
k3os version v0.11.1
5.4.0-48-generic #52 SMP Sat Sep 26 08:27:15 UTC 2020

**Architecture**
x86_64

**Describe the bug**
During boot the following error message is logged:

`Could not unmarshall userdata: invalid character '#' looking for beginning of value`

The cloud-init userdata looks like this:

```
#cloud-config
fqdn: k3s2.example.com
 
k3os:
  server_url: https://k3s1.example.com:6443
  token: "HIDDEN"
```

**To Reproduce**
Spin up a k3OS instance on a cloud which supports cloud-init userdata (e.g. OpenStack) and use the above documented userdata.

**Expected behavior**
The userdata script is unmarshalled without error message.

**Actual behavior**
Error is logged - but unmarshalling seems to still work as the configured options are properly applied.

**Additional context**
This was tested on cloudscale.ch which runs OpenStack behind the scenes.
