### ISSUE TITLE
DHCP provided properties ignored - e.g. hostname

### ISSUE THREAD

**Issue by sergeiwaigant** [rancher/k3os#641]
**Version (k3OS / kernel)**
k3os version v0.11.1 & latest v0.19.4-dev.5

**Architecture**
x86_64

**Describe the bug**
I am using pfSense as DHCP server and static mappings to assign IPs and other config like hostname to my systems.
For other systems, like Fedora or CentOS, which I bootstrap with PXE (syslinux) the OS is able to get everything from the DHCP provided data.
On the K3S machine its able to get the IP as expected, but the hostname and domain search list is ignored.
Furthermore it is setting the domain name as domain search list.

Funny enough... when just booting the ISO and run the install manually I can see, that the hostname is set correctly, but domain search list is still ignored.
Once installed, it is ignoring everything except the IP.

**To Reproduce**
- Setup pfSense as DHCP Server
- Configure static mapping with hostname option
- Start VM

My config.yml: 
```
ssh_authorized_keys:
- github:sergeiwaigant
boot_cmd: []
hostname: 
init_cmd: []

run_cmd:
- rc-service ntpd start
- sleep 5

k3os:
  data_sources:
  - aws
  environment: {}
  k3s_args:
  - "server"
  - "--cluster-domain=k3s.dus.waigant.io"
  - "--tls-san *.k3s.dus.waigant.io"

  ntp_servers:
  - 0.de.pool.ntp.org
  - 1.de.pool.ntp.org
  - 2.de.pool.ntp.org
  - 3.de.pool.ntp.org
```

My PXE Boot 
```
label k3os-0.19.4
  menu label ^Start & Install K3OS 0.19.4
  kernel http://truenas/pxeboot/k3os/v0.19.4/k3os-vmlinuz-amd64
  initrd http://truenas/pxeboot/k3os/v0.19.4/k3os-initrd-amd64,http://truenas/pxeboot/k3os/v0.19.4/k3os-rootfs-amd64.tar.gz,http://truenas/pxeboot/k3os/v0.19.4/k3os-kernel-version-amd64,http://truenas/pxeboot/k3os/v0.19.4/k3os-kernel-amd64.squashfs
  append ip=dhcp noipv6 ipv6.disable=1 k3os.mode=install k3os.install.device=/dev/sda k3os.install.no_format=false k3os.install.iso_url=https://github.com/rancher/k3os/releases/download/v0.19.4-dev.5/k3os-amd64.iso k3os.install.config_url=https://raw.githubusercontent.com/waigant/pxeboot/main/k3os/config.yml
```
**Expected behavior**
- Hostname and all DHCP options set as provided

**Actual behavior**
- Random hostname is chosen

**Additional context**
- ESXi v6.7U2
- pfSense 2.4.5
