### ISSUE TITLE
Some sysctl parameters are not applied

### ISSUE THREAD

**Issue by pvelati** [rancher/k3os#658]
**Version (k3OS / kernel)**
k3os version v0.11.1
5.4.0-48-generic #52 SMP Sat Sep 26 08:27:15 UTC 2020

**Architecture**
x86_64

**Describe the bug**
Some sysctl parameters are not applied when using cloud-config file for configuring the system.

**To Reproduce**
Create a cloud-config.yaml file adding the following snippet and install k3os 
```
k3os:
  sysctl:
    kernel.printk: "4 4 1 7"
    kernel.kptr_restrict: "1"
    net.core.somaxconn: "65535"
    vm.panic_on_oom: "1"
```

**Expected behavior**
```
$ sysctl -q kernel.printk net.core.somaxconn vm.panic_on_oom kernel.kptr_restrict
kernel.printk = 4       4       1       7
net.core.somaxconn = 65535
vm.panic_on_oom = 1
kernel.kptr_restrict = 1
```

**Actual behavior**
```
$ sysctl -q kernel.printk net.core.somaxconn vm.panic_on_oom kernel.kptr_restrict
kernel.printk = 1       4       1       7
net.core.somaxconn = 1024
vm.panic_on_oom = 0
kernel.kptr_restrict = 2
```

**Additional context**
Virtualized on Proxmox, using pxe boot install (tested also with iso install).
Tested also without "" for each parameters, same results.
I don't know if there are other parameters that cannot be applied.
