### ISSUE TITLE
feature request: support for regular cloud-init network config

### ISSUE THREAD

**Issue by christian-korneck** [rancher/k3os#66]
It would be great if it was possible to configure base networking settings (IP, gateway, dns domain, dns servers, hostname, search domains) through the regular cloud init interfaces (instead of having to create a `connman` service file).

Why is this important (in my opinion)? There are virtualization systems, like Proxmox VE, that allow you to configure a limited set of cloudimit parameters for a VM regarding the network config (but don't support full cloudinit scripts). This is usually enough to run any standard cloud image (Debian, CentOS, etc). It would be great if the `k3os` iso would behave similarly.

![image](https://user-images.githubusercontent.com/6320032/57092035-cbee3f80-6d0a-11e9-8176-f3e07df4f04b.png)

https://pve.proxmox.com/wiki/Cloud-Init_Support
https://pve.proxmox.com/wiki/Cloud-Init_FAQ

**Comment by axsc** [comment]
I stumbled upon the same issue.
Thumbs up :-)

**Comment by runningman84** [comment]
This would also help for cloud deployments in AWS

**Comment by BastienM** [comment]
> All configuration is done through a single cloud-init style config file

But `openrc` shows no trace of a `cloud-init` service at all, so it is safe to assume that k3os does use its own engine/service to execute the yaml upon runtime.

The cloud-init file would looks like this :

```
#cloud-config

hostname: <hostname>
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB...

config:
  user.network-config: |
    version: 1
    config:
      - type: physical
        name: eth0
        subnets:
          - type: dhcp

write_files:
  - path: /var/lib/rancher/k3os/config.yaml
  - owner: rancher:rancher
  - permissions: 0644
  - content: |
    k3os:
      data_sources:
        - cdrom
      modules:
        - kvm
    ...
 ```
 
Yet I am a bit divided on this, having both systems activated feels like an over-powered solution considering the initial scope of the project and could prove to be difficult to make the two living with each other. 

Maybe having a `cloud-init` flavored image would be simpler ?
