### ISSUE TITLE
Updates to proxy settings not propagating to k3s

### ISSUE THREAD

**Issue by joharper54SEG** [rancher/k3os#665]
**Version (k3OS / kernel)**
v0.19.5-rc.1

**Architecture**
x86_64

**Describe the bug**
I am using the k3os.environment option in the /var/lib/rancher/k3os/config.d/config.yaml to set http_proxy, https_proxy and no_proxy.  If I make changes to this config after initial settings have been set, the changes do not make it to k3s.  cattle-agent is unable to communicate with rancher and kubectl commands that go thru proxy begin to fail.

**To Reproduce**
Set proxy via config.yaml and confirm working
Change proxy in config.yaml, reboot
Proxy setting change did not take effect

Is there a way I can manually update the proxy k3s uses or tell k3s to relook at /etc/environment for updates?

**Comment by dweomer** [comment]
@joharper54SEG can you post a working/sample `config.yaml`?

**Comment by joharper54SEG** [comment]
Sure.  Here is the current YAML that we pull in during boot (scrubbed sensitive data out).  What I am doing is removing the *rancher.cloud param in no_proxy as I need that connection to go thru proxy now.  If I image the device with these settings all is fine.  If I change this on an existing node it's like it doesn't recognize new proxy settings.  Connections to rancher.cloud continue going direct to the internet and is being blocked.

```yaml
hostname: svr1

#set ssh keys
ssh_authorized_keys:
- ssh-rsa AAAAB3.

# apply k3os specific config
k3os:
  labels:
    location: "test"
  k3s_args:
  - "--node-name=svr1"
  environment:
    http_proxy: http://proxyserver.fqdn:8080
    https_proxy: http://proxyserver.fqdn:8080
    no_proxy: "NO_PROXY=localhost,127.0.0.1,localaddress,*.rancher.cloud,10.0.0.0/8"

#create config.sh script and write to disk
write_files:
  - encoding: ""
    content: |-
        #!/bin/bash
        sleep 7
        sudo wget --no-check-certificate -Y off https://svrcfg/svr1/svr1.yaml -O /var/lib/rancher/k3os/config.d/config.yaml
        sudo wget --no-check-certificate -Y off https://svrcfg/svr1/configmap.yaml -O /var/lib/rancher/k3s/server/manifests/configmaps.yaml
        sudo wget --no-check-certificate -Y off https://svrcfg/workloads-default.yaml -O /var/lib/rancher/k3s/server/manifests/workloads-default.yaml
        sudo wget --no-check-certificate -Y off https://svrcfg/upgradeplan.yaml -O /var/lib/rancher/k3s/server/manifests/upgradeplan.yaml

    owner: rancher
    path: /home/rancher/config.sh
    permissions: '0755'


run_cmd:
- sudo bash /home/rancher/config.sh
```
