### ISSUE TITLE
Improve documentation on k3os install for High Availability with Embedded DB

### ISSUE THREAD

**Issue by cdemi** [rancher/k3os#666]
I am experimenting with k3s in my homelab. I have managed to setup 1 server and 2 agents using the `k3os install` wizard. I have seen that in `v0.19.5-rc.1`, a multi-server or High Availability with Embedded DB configuration is supported.

I have been figuring out how to do this using k3os. I have spun up a new VM and it looks like the `k3os install` does not yet support this configuration, which is understandable since it's still in RC.

Is there any way I can achieve multi-server install using k3os? Or maybe promote my current agents to masters as well? If so, can you guide me on how to achieve this? Basically for my setup I plan to have all nodes act as server and master

**Comment by zimme** [comment]
First HA server node config
```
k3os:
  token: <token>
  k3sArgs:
    - server
    - --cluster-init
```
Other HA server nodes config
```
k3os:
  token: <token>
  k3sArgs:
    - server
    - --server
    - https://<first-server-url>:6443
```
This should be the bare minimum for embedded etc HA using latest k3os RC.

Here's some info on the k3s args used in the example.

https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

Tried this a while back and got it up and running, however wrote this post from memory so double check the args, etc.
Use at own risk, yada yada.

**Comment by cdeadspine** [comment]
Last confirmed with v0.19.5-rc.1
"Other HA server nodes config"
```
k3os:
  k3s_args:
  token: token
  server_url: https://192.168.10.43:6443
```
I think you have to use a hard coded ip or external dns of some type because mDNS is not standard?

Also you must have exactly 3 or more running. 2of2 running is failure condition, 1of3 running is failure condition
(something about how etcd works i think)

Also i don't remember why now, but I had to set for sure
```
k3os:
  dns_nameservers:
  - something
  ntp_servers:
  - something
```

**Comment by binayakd** [comment]
Can confirm the following configs are working for me with  `v0.21.1-k3s1r0`.

FIrst HA serve node:
```yaml
k3os:
  token: <token>
  
  k3s_args:
    - server
    - "--cluster-init"
    
  ntp_servers:
    # ntp servers if your choice
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org

  dns_nameservers:
    # dns servers of your choice
    - 8.8.8.8
    - 1.1.1.1
```

Rest of the HA nodes:
```yaml
k3os:
  token: <token>
  
  k3s_args:
    - server
    - "--server"
    - "https://<first HA server node IP>:6443"
    
  ntp_servers:
    # ntp servers if your choice
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org

  dns_nameservers:
    # dns servers of your choice
    - 8.8.8.8
    - 1.1.1.1
```
the `k3os.server_url` prop is not needed for any of the nodes.
