### ISSUE TITLE
What is the dealio - Cloud-Init directives being ignored

### ISSUE THREAD

**Issue by DarkBlaez** [rancher/k3os#670]
All:

This seems to be problematic from release to release. I have watched this issue arise constantly. Why is the cloud-init directives being ignored in v0.11.1?

```
k3os:
  k3s_args:
  - server
  - “--disable=servicelb,traefik”
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  password: rancher
  token: xxxxxx
```
The amount of tie I have spent on this is ridiculous. Others have experienced this issue. I have experienced this issue in the past only to discover that the documentation was not updated. Someone needs to quit fiddling with this.

servicelb appears like it is not running yet Traefik is. Back when I was up under v0.11.0 the above format worked. Now for some reason the behavior is not as expected.

Please advise

Thanks
DB

**Comment by kphunter** [comment]
I had better success moving the `k3s_args` block to the bottom... also, check that you're using "simple ASCII quotes" for any flags

**Comment by DarkBlaez** [comment]
I will try to roll this back in v0.11.0 and see if the original still works. Along with moving the k3s_args to the bottom. From what I can tell I am using simple quotes.

**Comment by DarkBlaez** [comment]
Seems it is a v0.11.1 issue. This works just fine under v0.11.0. I have seen this numerous times across releases. A bit more thorough testing prior to releases might actually help avoid individuals spending hours with what amounts to an induced bug. I'll stick with v0.11.0 for now.

DB

**Comment by DarkBlaez** [comment]
Seems like moving it to the end and even rolling back things still do not work correctly. servicelb and traefik continue to get deployed.

Devs - Spend more time on the parser within the k3os installer and fix this. The ass-pains this causes and has caused for many revs back, including the disconnect with documentation is causing many hours of frustration and recycle installs.

DB

**Comment by dweomer** [comment]
Please ensure that `sudo k3os config --dump` returns without error. This is my first diagnostic with behavior re: `config.yaml`

**Comment by DarkBlaez** [comment]
Yes have done that, everything is fine, no issues. It returns with no errors. 

```  k3s_args:
  - server
  - “--disable=traefik,servicelb”
```

this disable directive is being ignored. The config is processed without errors. As such this is a problem within the installer. I saw this in 2020 when there was a disconnect with the documentation and what was implemented. This chasing my tail constantly with this is annoying. Many have posted issues with the processing of the cloud-init. Is there anyone having a look at this? It seems to be recurring, almost to the point where there needs to be a separate iso without traefik and servicelb as most seem to be attempting to disable it. Make it a toggled option to install the pair or through code omit with a single flag upon install

DB

**Comment by DarkBlaez** [comment]
Closing this

**Comment by dweomer** [comment]
@DarkBlaez it may be worth considering to try one of the 0.19.x series development/release-candidate builds. I am not sure where the weirdness and inconsistencies come from. When I have the time to work on k3OS I try to make sure that the things I need from it work correctly (and this is one of them). I run v0.19.5-rc.1 on some NUCs in my homelab with a `config.yaml` (on the initial HA leader):
```yaml
hostname: nuc-1

k3os:
  k3s_args:
  - server
  - --cluster-init
  - --disable=servicelb,local-storage
  password: rancher
  token: homelab

boot_cmd:
- mount /dev/sda1 /var/lib/longhorn

run_cmd:
- rc-service ntpd start

ssh_authorized_keys:
- github:dweomer
```

... and the resulting `/etc/init.d/k3s-service`:

```bash
#!/sbin/openrc-run

depend() {
    after network-online
    want cgroups
}

start_pre() {
    rm -f /tmp/k3s.*
}

supervisor=supervise-daemon
name=k3s-service
command="/sbin/k3s"
command_args="server \
	'--cluster-init' \
	'--disable=servicelb,local-storage' \
	'--node-label' \
	'k3os.io/mode=local' \
	'--node-label' \
	'k3os.io/version=v0.19.5-rc.1' \
    >>/var/log/k3s-service.log 2>&1"

output_log=/var/log/k3s-service.log
error_log=/var/log/k3s-service.log

pidfile="/var/run/k3s-service.pid"
respawn_delay=5
respawn_max=0

set -o allexport
if [ -f /etc/environment ]; then source /etc/environment; fi
if [ -f /etc/rancher/k3s/k3s-service.env ]; then source /etc/rancher/k3s/k3s-service.env; fi
set +o allexport
```
