### ISSUE TITLE
Cloud-init file is not being taken

### ISSUE THREAD

**Issue by dharmendrakariya** [rancher/k3os#671]
**Version (k3OS / kernel)**

k3os-version: Tried with v0.11.1/v0.11.0/v0.19.5-rc-1

kernel-version: 5.4.0-54-generic

**Architecture**

x86_64

**Describe the bug**

I am trying to create 3 node HA Cluster with the help of cloud-init, but cloud-init is not being taken during boot process.

**To Reproduce**

```
ssh_authorized_keys:
- "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAw4MfpvpJp71VJewSiwxbS36mqU5FGbEf"
- github:dharmendrakariya
hostname: node1
k3os:
  data_sources:
  - aws
  - cdrom
  modules:
  - kvm
  - nvme
  sysctl:
    kernel.printk: "4 4 1 7"
    kernel.kptr_restrict: "1"
  dns_nameservers:
  - 10.0.1.1
  - 8.8.8.8
  ntp_servers:
  - 0.in.pool.ntp.org
  - 1.in.pool.ntp.org

  token: secrets
 
  k3s_args:
  - server
  - --cluster-init
  - --node-name=node1

 ```
I am using the above cloud-init and using pastebin.com( https://pastebin.com/raw/_randomGeneratedString_ ) while giving the cloud-init url. but after giving the url, it finishes off the booting and again the menu comes to choose the boot process with three options like : ```live CD or installaton```, ```K3os installer``` or ```k3os rescue mode``` instead, it supposed not to give that window again and installation should be succeeded right!

**Expected behavior**

The host-name, ssh access, and k3s_args should be reflected

**Actual behavior**

Not ```host-name``` changed, no ```ssh access```, no ```"--cluster-init"``` flag flound in ```/etc/init.d/k3s-service```  

**Additional context**
```sudo k3os config --dump``` returns ``` k3os: { } ```

Can you please direct me in the working process??
