### ISSUE TITLE
Configure 5.0ghz wifi on ARM overlay installation

### ISSUE THREAD

**Issue by xinbinhuang** [rancher/k3os#835]
Hi, 

thanks for the great work! Recently, I've used this project https://github.com/sgielen/picl-k3os-image-generator to install k3os on two raspberry pi 4. Currently, I'm using WIFI to connect to internet, but I noticed they connect to the 2.4 GHz band instead of the 5.0ghz. Do you know if there is a way to configure it to use 5.0ghz?

Thanks!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
I've tried written the country code to `config.yaml`, but it doesn't help :(.

```
write_files:
  - path: /etc/wpa_supplicant/wpa_supplicant.conf
    content: |-
      country=US
```

**Additional context**
version : v0.21.5-k3s2r1
