### ISSUE TITLE
Boot_cmd running after write_files

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3os#93]
Version - v0.2.1-rc2

Steps:
1.  Create a config.yaml with
```
write_files:
- enconding: ""
  content: |
    Here is a line.
    Another line is here
  owner: root
  path: test2.txt
  permissions: '0777'
run_cmd:
- "echo 'run hello' >> test2.txt"
boot_cmd:
- "echo 'boot hello' >> test2.txt"
k3os:
  password: asdf
```
2.  During boot process, press e to get into GNU Grub
3.  On linux cmdline add k3os.mode=install k3os.install.config_url="config yaml url"
4.  Log in and cat/test2.txt

results:
```
Here is a line
Another line is here
run hello
```

Expected:  Documentation says that boot, run and init command run after the write_files.  So I would expect to see the "boot hello" text in there as well.  If I run the boot_cmd to a different file it shows up.
