### ISSUE TITLE
ntp isn't working on server

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3os#94]
Version - v0.2.1-rc1
1.  Create a config.yaml with
```
k3os:
  password: asdf
  ntp_servers:
  - time.apple.com
```
2.  During boot process, press e to get into GNU Grub
3.  On linux cmdline add k3os.mode=install k3os.install.config_url="config yaml url"
4.  Log in and ntpstat

results:  command not found.
