### ISSUE TITLE
dns_nameservers not working when set through the config.yaml

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3os#96]
Version - v0.2.1-rc1

1.  Create a config.yaml with
```
k3os:
  dns_nameservers:
  - 1.1.1.1
  password: asdf
```
2.  During boot process, press e to get into GNU Grub
3.  On linux cmdline add k3os.mode=install k3os.install.config_url="config yaml url"
4.  Log in and cat /etc/resolv.conf

Results:  1.1.1.1 is not in list of namespaces.  I also looked in the /etc/connman/main.conf and it wasn't in there either.
