### ISSUE TITLE
k3os.environment is not populating k3s-service.env file

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3os#98]
Version - v0.2.1-rc2

Steps:
1.  Create a config.yaml with
```
k3os:
  password: rancher
  environment:
    http_proxy: http://1.1.1.1:8888
```
2.  During boot process, press e to get into GNU Grub
3.  On linux cmdline add k3os.mode=install k3os.install.config_url="config yaml url"
4.  Log in and ```sudo cat /etc/rancher/k3s/k3s-service.env```

Results:  Environment not showing up.  I tried set this for a proxy setup and couldn't get it to work.

**Comment by pagong** [comment]
True, there is no code in 'pkg' directory to write the environment from `config.yaml` into `/etc/environment` or `/etc/rancher/k3s/k3s-service.env`.

As work-around those files could be populated with `write_files` statements.

**Comment by pagong** [comment]
The `environment` part in this example `config.yaml`  DOES not set the http proxies.
```
hostname: rancher
k3os:
  install: {}
  password: R4ncher
  environment:
    http_proxy: http://192.168.107.9:8080
    https_proxy: http://192.168.107.9:8080
  k3s_args:
  - server
  - "--cluster-cidr 10.107.0.0/23"
  - "--service-cidr 10.107.1.0/23"
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCi5qtxRWqg9tcUzrxE1pk57TmBIZy+YKQ9m/BIp6W0WWrUIBgort6M  ...   sYLkEnvXj09JmmTprvBO9c7x+Wq2EV7GmwJ5yy4a/YMyTP/69 pagong
write_files:
  - enconding: ""
    content: |
      http_proxy=http://192.168.107.9:8080
      https_proxy=http://192.168.107.9:8080
    path: /etc/environment
    owner: root
    permissions: '0644'
```
But the `write_files` section does have the desired result:
```
rancher [/tmp]$ kubectl cluster-info 
Kubernetes master is running at https://localhost:6443
CoreDNS is running at https://localhost:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

rancher [/tmp]$ kubectl get nodes 
NAME      STATUS   ROLES    AGE   VERSION
rancher   Ready    <none>   97s   v1.14.1-k3s.4

rancher [/tmp]$ kubectl get pods -A
NAMESPACE     NAME                         READY   STATUS      RESTARTS   AGE
kube-system   coredns-695688789-lph6j      1/1     Running     0          5m47s
kube-system   helm-install-traefik-z6n78   0/1     Completed   0          5m48s
kube-system   svclb-traefik-czhbf          2/2     Running     0          3m44s
kube-system   traefik-55bd9646fc-c7psx     1/1     Running     0          3m44s
```
