### ISSUE TITLE
Some config options don't work when installing on aws

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3os#99]
Version - v0.2.1-rc2
1.  Create a config.yaml file with:
```
hostname: myhost
boot_cmd:
- "echo 'boot hello' >> test2.txt"
k3os:
  modules:
  - gre
  k3_args:
  - server
  - "--no-deploy traefik"
```
2.  Go to AWS and select the k3os ami
3.  Select a medium size machine
4.  In Config, Advanced Options, select the config.yaml file
5.  Finish and ssh into the instance

Results:  hostname, boot_cmd, k3os.modules, k3os.k3_args are not working.
